### ISSUE TITLE
Tensorboard

### ISSUE THREAD

**Issue by brianprichardson** [trebledawson/chess#4]
It is creating update files in the .\TensorBoard directory, but the web page says inactive.  Also file sizes are growing and up to about 400MB each

**Comment by trebledawson** [comment]
I do not know what the problem may be with TensorBoard; it is possible that you may need to change some things in your files if you are not working on Windows.

File sizes are expected to grow very large; this is an unfortunate side effect of how I wrote the data cleaning script.

**Comment by brianprichardson** [comment]
Ah, forgot about Windows.  Just renamed the directory and it works.
